###

POST http://localhost:10090/spring-kafka/kafka/message
Content-Type: application/json

{
  "eventType": "TEXT",
  "data": "Hello Wayne"
}

> {%
    client.test("Text message published", function() {
        client.assert(response.status === 201, "Text message not published");
    });
%}

###

POST http://localhost:10090/spring-kafka/kafka/order
Content-Type: application/json

{
  "eventType": "ORDER_SUBMITTED",
  "data": {
    "id": "MyTimeline"
  }
}

> {%
    client.test("Order submitted notification published", function() {
        client.assert(response.status === 201, "Order submitted notification not published");
    });
%}

###

POST http://localhost:10090/spring-kafka/kafka/order
Content-Type: application/json

{
  "eventType": "UNSUPPORTED",
  "data": {
    "id": "MyTimeline"
  }
}

> {%
    client.test("Unsupported event published", function() {
        client.assert(response.status === 400, "Failed to reject unsupported event");
    });
%}